-- http://geonames.usgs.gov/
-- http://www.itl.nist.gov/fipspubs/fip55-3.htm
WITH SRC (SequenceNumber, FIPSCode, AlphaCode, LocationName) AS
(
SELECT 1, '01', 'AL', 'Alabama'
UNION ALL SELECT 2, '02', 'AK', 'Alaska'
UNION ALL SELECT 3, '04', 'AZ', 'Arizona'
UNION ALL SELECT 4, '05', 'AR', 'Arkansas'
UNION ALL SELECT 5, '06', 'CA', 'California'
UNION ALL SELECT 6, '08', 'CO', 'Colorado'
UNION ALL SELECT 7, '09', 'CT', 'Connecticut'
UNION ALL SELECT 8, '10', 'DE', 'Delaware'
UNION ALL SELECT 9, '11', 'DC', 'District of Columbia'
UNION ALL SELECT 10, '12', 'FL', 'Florida'
UNION ALL SELECT 11, '13', 'GA', 'Georgia'
UNION ALL SELECT 12, '15', 'HI', 'Hawaii'
UNION ALL SELECT 13, '16', 'ID', 'Idaho'
UNION ALL SELECT 14, '17', 'IL', 'Illinois'
UNION ALL SELECT 15, '18', 'IN', 'Indiana'
UNION ALL SELECT 16, '19', 'IA', 'Iowa'
UNION ALL SELECT 17, '20', 'KS', 'Kansas'
UNION ALL SELECT 18, '21', 'KY', 'Kentucky'
UNION ALL SELECT 19, '22', 'LA', 'Louisiana'
UNION ALL SELECT 20, '23', 'ME', 'Maine'
UNION ALL SELECT 21, '24', 'MD', 'Maryland'
UNION ALL SELECT 22, '25', 'MA', 'Massachusetts'
UNION ALL SELECT 23, '26', 'MI', 'Michigan'
UNION ALL SELECT 24, '27', 'MN', 'Minnesota'
UNION ALL SELECT 25, '28', 'MS', 'Mississippi'
UNION ALL SELECT 26, '29', 'MO', 'Missouri'
UNION ALL SELECT 27, '30', 'MT', 'Montana'
UNION ALL SELECT 28, '31', 'NE', 'Nebraska'
UNION ALL SELECT 29, '32', 'NV', 'Nevada'
UNION ALL SELECT 30, '33', 'NH', 'New Hampshire'
UNION ALL SELECT 31, '34', 'NJ', 'New Jersey'
UNION ALL SELECT 32, '35', 'NM', 'New Mexico'
UNION ALL SELECT 33, '36', 'NY', 'New York'
UNION ALL SELECT 34, '37', 'NC', 'North Carolina'
UNION ALL SELECT 35, '38', 'ND', 'North Dakota'
UNION ALL SELECT 36, '39', 'OH', 'Ohio'
UNION ALL SELECT 37, '40', 'OK', 'Oklahoma'
UNION ALL SELECT 38, '41', 'OR', 'Oregon'
UNION ALL SELECT 39, '42', 'PA', 'Pennsylvania'
UNION ALL SELECT 40, '44', 'RI', 'Rhode Island'
UNION ALL SELECT 41, '45', 'SC', 'South Carolina'
UNION ALL SELECT 42, '46', 'SD', 'South Dakota'
UNION ALL SELECT 43, '47', 'TN', 'Tennessee'
UNION ALL SELECT 44, '48', 'TX', 'Texas'
UNION ALL SELECT 45, '49', 'UT', 'Utah'
UNION ALL SELECT 46, '50', 'VT', 'Vermont'
UNION ALL SELECT 47, '51', 'VA', 'Virginia'
UNION ALL SELECT 48, '53', 'WA', 'Washington'
UNION ALL SELECT 49, '54', 'WV', 'West Virginia'
UNION ALL SELECT 50, '55', 'WI', 'Wisconsin'
UNION ALL SELECT 51, '56', 'WY', 'Wyoming'

UNION ALL SELECT 52, '60', 'AS', 'American Samoa'
UNION ALL SELECT 54, '66', 'GU', 'Guam'
UNION ALL SELECT 56, '69', 'MP', 'Northern Mariana Islands'
UNION ALL SELECT 58, '72', 'PR', 'Puerto Rico'
UNION ALL SELECT 59, '74', 'UM', 'U.S. Minor Outlying Islands'
UNION ALL SELECT 60, '78', 'VI', 'Virgin Islands of the U.S.'

UNION ALL SELECT 53, '64', 'FM', 'Federated States of Micronesia'
UNION ALL SELECT 55, '68', 'MH', 'Marshall Islands'
UNION ALL SELECT 57, '70', 'PW', 'Palau'

-- Not FIPS but helpful
UNION ALL SELECT 200, 'AB', 'AB', 'Alberta'
UNION ALL SELECT 201, 'BC', 'BC','British Columbia'
UNION ALL SELECT 202, 'MB', 'MB','Manitoba'
UNION ALL SELECT 203, 'NB', 'NB','New Brunswick'
UNION ALL SELECT 204, 'NL', 'NL','Newfoundland'
UNION ALL SELECT 205, 'NS', 'NS','Nova Scotia'
UNION ALL SELECT 206, 'NT', 'NT','Northwest Territory'
UNION ALL SELECT 207, 'NU', 'NU','Nunavut'
UNION ALL SELECT 208, 'ON', 'ON','Ontario'
UNION ALL SELECT 209, 'PE', 'PE','Prince Edward Island'
UNION ALL SELECT 210, 'QC', 'QC','Quebec'
UNION ALL SELECT 211, 'SK', 'SK','Saskatchewan'
UNION ALL SELECT 212, 'YT', 'YT','Yukon Territory'
)
SELECT
    SRC.SequenceNumber
,   SRC.FIPSCode
,   SRC.AlphaCode
,   SRC.LocationName
FROM 
    SRC AS SRC;